Added the system for distributing prizes, uses weighted random item generation (and some java because it was easier in Java than bash)

diff --git a/give-points b/give-points
--- a/give-points
+++ b/give-points
@@ -6,6 +6,14 @@ if [ "$#" == "0" -o "$#" -gt "2" ]; then
 fi
 GIVER=$(whoami)
 TARGET="$1"
+if [ -z "$(grep $GIVER $MEMBERS_LIST)" ]; then
+  echo "you are not a member of the points system, please notify the administrators"
+  exit 1
+fi
+if [ -z "$(grep $TARGET $MEMBERS_LIST)" ]; then
+  echo "$TARGET is not a member of the points system. If you believe this is in error, please notify the administrators"
+  exit 1
+fi
 if [ "$#" == "2" ]; then
   if echo -n "$2" | grep -q "^[1-9][0-9]*$"; then
     POINTS="$2"
